language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
   - SYMFONY_VERSION=2.3.*
   - SYMFONY_VERSION=2.7.*

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --no-update --dev
  - php composer.phar update --prefer-dist --no-interaction --dev

script:
  - vendor/bin/coke
  - vendor/bin/atoum
